### ISSUE TITLE
Uncaught Error: listen EADDRINUSE /tmp/voicecode-atom.sock

### ISSUE THREAD

**Issue by david-tejada** [VoiceCode/atom-voicecode#2]
[Enter steps to reproduce below:]

I get this error almost every day, I don't know what triggers it. I just fired up Atom and there it was. spring, sprinkler, wordneck,... stop working.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [voicecode](https://github.com/VoiceCode/atom-voicecode) package, v0.10.2
### Stack Trace

Uncaught Error: listen EADDRINUSE /tmp/voicecode-atom.sock

```
At events.js:141

Error: listen EADDRINUSE /tmp/voicecode-atom.sock
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1158:19)
    at listen (net.js:1203:10)
    at Server.listen (net.js:1284:5)
    at /Users/David/.atom/packages/voicecode/lib/voicecode.coffee:51:29
    at FSReqWrap.oncomplete (fs.js:77:15)
```
### Commands

```
     -0:12.6.0 voicecode:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
voicecode, v0.10.2

# Dev
No dev packages
```

**Comment by unboundmusic** [comment]
When this happens are there multiple atom windows open? or just a single window?

**Comment by david-tejada** [comment]
Yes, multiple. Also, if when I open Atom there's just one window spring and the other commands work. If I open other windows they also work. But if when I open Atom there's more than one window the commands only work in one of them, usually the one that was at the front at the beginning.

**Comment by unboundmusic** [comment]
I fixed the issue - it should now work properly with multiple windows, and automatically send the commands to the active window, without requiring you to run the "connect" command each time you switch to a different window. Make sure to update the package in Atom.

**Comment by david-tejada** [comment]
Everything seems to be working fine now. Thanks, man.

**Comment by david-tejada** [comment]
I'm still getting the error alert. Everything is working as intended now, but every time I open Atom for the first time after starting up the computer I get the error alert. It doesn't happen if I just quit Atom and then open it again.

**Comment by rschaaf** [comment]
I'm getting the same error alert.  Here's what I see when I open Atom: 

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [voicecode](https://github.com/VoiceCode/atom-voicecode) package, v0.11.0

### Stack Trace

Uncaught Error: listen EADDRINUSE /tmp/voicecode-atom.sock

```
At events.js:141

Error: listen EADDRINUSE /tmp/voicecode-atom.sock
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1158:19)
    at listen (net.js:1203:10)
    at Server.listen (net.js:1284:5)
    at /Users/robertschaaf/.atom/packages/voicecode/lib/voicecode.coffee:53:29
    at FSReqWrap.oncomplete (fs.js:77:15)
```

### Commands

```
     -0:02.2.0 voicecode:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
voicecode, v0.11.0

# Dev
No dev packages
```

**Comment by rschaaf** [comment]
"Spring" and other commands are working though.

**Comment by dmose** [comment]
Hmm, just installed the voicecode package in Atom for the first time, and I'm seeing this too.

I only have a single window open.

**Comment by dimatter** [comment]
@dmose but everything works after that, right?

**Comment by dmose** [comment]
Good question.  On subsequent startups, I haven't been seeing it, and I'm still brand new to Atom.

**Comment by unboundmusic** [comment]
I believe this should be fixed now

**Comment by pimentel** [comment]
it certainly appears less now, but unfortunately I'm still having this issue :(
